frontend/controllers/AdminController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\PhotoUpdate;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AdminController implements the CRUD actions for PhotoUpdate model.
 */
class AdminController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PhotoUpdate models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PhotoUpdate::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PhotoUpdate model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PhotoUpdate model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PhotoUpdate();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing PhotoUpdate model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PhotoUpdate model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PhotoUpdate model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PhotoUpdate the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PhotoUpdate::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionApproval()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PhotoUpdate::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);


        return $this->render('index',[
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndividual()
    {
        return $this->render('individual_req');
    }


    public function actionAdmin()
    {
       return $this->render('admin'); 
    }

    public function actionPhotoUpdate()
    {
        return $this->render('photo_update');    
    }

    public function actionCheckPhoto()
    {
        return $this->render('check_photo');    
    }
}

frontend/views/admin/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\PhotoUpdate */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="photo-update-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'timestamp')->textInput() ?>

    <?= $form->field($model, 'photo_url')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/admin/admin.php
<?php use yii\helpers\Html;
 ?>


 <?php $user=Yii::$app->user->identity; ?>
<h1> <?php echo 'Name: '.$user->firstname.' '.$user->lastname  ?> </h1>
<br>
<br>
<br>
<div align="center">
	<?= Html::a('Approval', ['/admin/approval'], ['class'=>'btn btn-primary btn-lg']) ?>

	<?= Html::a('Photo Update', ['/admin/photo-update'], ['class'=>'btn btn-info btn-lg ']) ?>
</div>

frontend/views/admin/approval.php
<?php 
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;


$this->title = 'Photo Update Approval';
$user = Yii::$app->user->identity;
 ?>


 <div class="admin-approval">
 	
 	<?php if(!Yii::$app->user->isGuest): ?>
 		<div class="container">
            <h1> <?php echo "Photo Update Requests" ?> </h1>
            
            <?php 
            	echo GridView::widget([
				    'dataProvider' => $dataProvider,
				    'columns' => [
				        ['class' => 'yii\grid\SerialColumn'],
				        // Simple columns defined by the data contained in $dataProvider.
				        // Data from the model's column will be used.
				        // 'id',
				        [
				         'label' => 'Name',
				         'value' => function ($model) {
				             return $model->getFullname($model->user_id);
				         }
				       ],
				        'timestamp',
				     	[
						  'class' => 'yii\grid\ActionColumn',
						  'header' => 'Actions',
						  'headerOptions' => ['style' => 'color:#337ab7'],
						  'template' => '<div class="text-center" role="group">{view}{delete}',
						  'buttons' => [
						    'view' => function ($url, $model) {
						        return Html::a( '<span class="glyphicon glyphicon-eye-open"></span>' , ['admin/check-photo']);
						    },

						    'delete' => function ($url, $model) {
						         return Html::a( '<span class="glyphicon glyphicon-trash"></span>' , Yii::$app->request->referrer);
						    }

						  ],
						  
						  ],
				        
				    ],
				]);
             ?>
        </div>
 	<?php endif ?>

 </div>

frontend/views/admin/check_photo.php
<?php 
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;


$this->title = 'Photo Update Approval';
$user = Yii::$app->user->identity;
 ?>


 <div class="admin-approval">
 	
 	<?php if(!Yii::$app->user->isGuest): ?>
 		<div class="container">
            <h1> <?php echo "Course: ITS100" ?> </h1>
            <h3> <?php echo "Section: 3" ?> </h3>
            <h1> <?php echo 'Name: '.$user->firstname.' '.$user->lastname  ?> </h1>

            <?php 
    //         	echo GridView::widget([
				//     'dataProvider' => $dataProvider,
				//     'columns' => [
				//         ['class' => 'yii\grid\SerialColumn'],
				        
				//         'username',
				//         'firstname',
				//         'lastname',
				        
				//         [
				//             'class' => 'yii\grid\CheckboxColumn',
				//         ],
				//     ],
				// ]);
             ?>
        </div>
 	<?php endif ?>

 </div>

frontend/views/admin/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\PhotoUpdate */

$this->title = 'Create Photo Update';
$this->params['breadcrumbs'][] = ['label' => 'Photo Updates', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photo-update-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/admin/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Photo Updates';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photo-update-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Photo Update', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
                        
            ['class' => 'yii\grid\SerialColumn'],

            
            [
            'label' => 'Name',
            'value' => function ($model) {
            return $model->getFullname($model->user_id);
            }
            ],
            'timestamp',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

frontend/views/admin/individual_req.php
<div class ="row">
  <div class="col-md-9">
   <h1>Name: Nawaphat  Aroijung<br>
   <h1>Student ID: 5822770169</h1><br>
   <h4>Last Update: 15.34 pm</h4>
  </div>
  <div class="col-md-3"><div class="pull-right">
   <img src="../../web/images/profile.png" style="width:230px;height:230px">
  </div>
  </div>
</div>
<div class="row">
  <div class="col-md-9">          
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
  </table>
</div>
  </div>
  
</div>

frontend/views/admin/photo_update.php
<?php 
use yii\helpers\Html;
use yii\helpers\Url;

$this->registerJsFile(Url::to('@web/js/slide_div.js'), ['depends' => [\yii\web\JqueryAsset::className()]]);

 ?>

<form>
	<br> 
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
  <div align="center">
    <label for="exampleFormControlFile1"><h3>Choose your image</h3></label>
  </div>
</form>

<div align="center">
<!DOCTYPE html>
<html>
<head>
<link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
<meta charset=utf-8 />
<title>JS Bin</title>
<!--[if IE]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<style>
  article, aside, figure, footer, header, hgroup, 
  menu, nav, section { display: block; }
</style>
</head>
<body>
  <input type='file' onchange="readURL(this);" />
    <img id="show_image" src="#" alt="your image" />
</div> 
</body>
</html>

frontend/views/admin/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\PhotoUpdate */

$this->title = 'Update Photo Update: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Photo Updates', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="photo-update-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/admin/view.php
w44 <?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\PhotoUpdate */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Photo Updates', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photo-update-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' =>  $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post', 
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'timestamp',
            'photo_url:ntext',
            'status',
        ],
    ]) ?>

</div>